import enLocale from 'element-ui/lib/locale/lang/en'
import zhLocale  from 'element-ui/lib/locale/lang/zh-CN'

export default  {
  en: {
    loadingText:"loading...",
    emptyText:"No Data",
    language:"中文",
    search:"Search",
    reset:"Reset",
    changePwd:"Change Password",
    logout:"Logout",
    operation:"Operation",
    terOpt:'Terminal Operation',
    perOpt:'Param Operation',
    ok:"Ok",
    cancel:"Cancel",
    oldPwd:"Old Password",
    newPwd:"New Password",
    confirmPwd:"Confirm Password",
    prompt:"Prompt",
    exitConfirm:"Are you sure to exit the system？",
    pwdValidMsg:"two input password inconsistencies",
    remark:"Remark",
    selectFile:"Select File",
    selectOneFile:'please select one file',
    selectDate:"Select Date",
    selectOneData:"Please choose at least one data",
    version:"Version",
    downloadFlag:"Download Flag",
    forceDownload:"Force Download",
    unforcedDownload:"Unforced Download",
    createTime:"CreateTime",
    updateTime:"UpdateTime",
    hasTerminal:"There is no device",
    selectData:"Please select a piece of data",
    tel:"Tel",
    address:"Address",
    linkman:"Linkman",
    deviceSn:"Terminal Serial",
    mchnt:"Merchant Name",
    requiredBlur:"This field is required.",
    length32:"Please enter no more than 32 characters.",
    length64:"Please enter no more than 64 characters.",
    length128:"Please enter no more than 128 characters.",
    length256:"Please enter no more than 256 characters.",
    phone:"Please enter a valid phone number.",
    number:"Please enter a valid number.",
    numAndEn:"Please enter number or english.",
    versionRules:"Please enter a valid version.",
    seri:"NO",
    noDev:"this group has no terminal！",
    selDev:"this group terminal has been selected!",
    AddSuccess:"Add Success",
    noTernimal:"There is no device",
    systemManage: {
      role:{
        searchLabel:"Name",
        searchPlaceHolder:"enter role name",
        addFormTitle:"add role",
        editFormTitle:"edit role",
        configFormTitle:"Assign permissions",
        fieldId:"Id",
        fieldname:"Name",
        deleteConfirm:"Are you sure to delete this role?"
      },
      operator:{
        username:"Username",
        realname:"Realname",
        role:"Role",
        organization:"Organization",
        tel:"Tel",
        status:"Status",
        usernamePlace:"enter username",
        realnamePlace:"enter realname",
        addFormTitle:"add user",
        editFormTitle:"modify user",
        deleteConfirm:"Are you sure to delete this user?",
        unlockConfirm:"Are you sure to unlock this user?",
        resetConfirm:"Are you sure to reset this user?"
      },
      org:{
        searchPlace:"enter organization name",
        level:"Level",
        name:"Name",
        id:"Id",
        type:"Type",
        addFormTitle:"add organization",
        editFormTitle:"modify organization",
        parentOrg:"Parent Org",
        deleteConfirm:"Are you sure to delete this organization?",
      },
      log:{
        username:"Name",
        namePlace:"enter operator name",
        status:"Status",
        operate:"Operate",
        time:"Time",
        org:"Organization",
        ip:"Ip"
      }
    },
    appManage:{
      app:{
        key:"key",
        nameLabel:"Name",
        statusLabel:"Status",
        searchPlace:"enter application name",
        name:"Application Name",
        brandName:"Manufacturer",
        terminalType:"Terminal Type",
        terminalModel:"Terminal Model",
        applicationIcon: "Application Icon",
        status:"Status",
        addFormTitle:"add application",
        editFormTitle:"modify application",
        selectTerminal:"select terminal",
        packageDetails:"application package details",
        addpackageFormTitle:"add application package",
        selectPackage:"application package",
        download:"Download",
        downloadConfirm:"Are you sure to download this application package?",
        deleteConfirm:"Are you sure to delete this application?",
        onlineConfirm:"Are you sure to online this application?",
        outlineConfirm:"Are you sure to offline this application?",
        deletePkgConfirm:"Are you sure to delete this application package?"
      },
      firmWare:{
        nameLabel:"FirmWare Name",
        namePlace:"enter firmWare name",
        nameVersion:"enter firmWare version",
        addFormTitle:"add firmWare",
        onlineConfirm:"Are you sure to online this firmWare?",
        outlineConfirm:"Are you sure to offline this firmWare?",
        id:"Id",
        FolderPath:"FolderPath",
        FilePath:"FilePath",
        status:"Status",
        download:"download",
        selectFirmWare:"Select FirmWare",
        deleteConfirm:'Are you sure to delete this firmWare?'
      },
      document:{
        searchLabel:"Document Name",
        searchPlaceHolder:"enter document name",
        importFormTitle:"Import Document",
        selectKey:"Select Document",
        docName:"Document Name",
        docDesc:"Document Description",
        createdDatetime:"Create Time",
        deleteConfirm:'Are you sure to delete this document?'
      }
    },
    parameterManage:{
      para:{
        serialLabel:"Terminal Serial",
        versionLabel:"Terminal Version",
        serialPlace:"enter terminal serial",
        versionPlace:"enter terminal version",
        TPDU:"TPDU",
        addFormTitle:"add terminal parameter",
        addTpduFormTitle:"add tpdu parameter",
        addMchntFormTitle:"add merchant parameter",
        editMchntFormTitle:"modify merchant parameter",
        terminalSerial:"Terminal Serial",
        serverParameter:"Server Parameter",
        serverParameter1:"Server Parameter Bak1",
        serverParameter2:"Server Parameter Bak2",
        deleteConfirm:"Are you sure to delete this parameter?",
        tpduDetails:"terminal tpdu parameter",
        mchntDetails:"terminal mchnt parameter",
        code:"Code",
        value:"Val",
        type:"Type",
        currency:"Currency",
        mchntName:"Merchant Name"
      },
      posp:{
        paramNo:"Number",
        paramType:"Type",
        paramVer:"Version",
        createOprater:"Operator",
        paramVal:"Value",
        addFormTitle:"add posp parameter",
        editFormTitle:"modify posp parameter",
        deleteConfirm:"Are you sure to delete this parameter?"
      }
    },
    terminalManage:{
      brand:{
        searchLabel:"Manufacturer",
        searchPlace:"enter Manufacturer",
        addFormTitle:"add Manufacturer",
        editFormTitle:"edit Manufacturer",
        deleteConfirm:"Are you sure to delete this Manufacturer?",
        name:"Manufacturer name"
      },
      model:{
        type:"Terminal Type",
        model:"Terminal Model",
        addFormTitle:"add model",
        editFormTitle:"edit model",
        deleteConfirm:"Are you sure to delete this model?",
      },
      devGroup:{
        searchLabel:"Group Name",
        searchPlaceHolder:"enter group Name",
        modleName:"Model Name",
        creOpt:"Create Operator",
        addFormTitle:"add group",
        termModel:"Terminal Model",
        selGroup:"Select Group",
        transPlace:"enter Terminal Serial Number",
        copyModel:"Copy All Data from Other Group/Terminal",
        deviceSn:"Terminal Serial Number",
        addGroupTitle:"Copy All Data",
        devGroupTitle:'Confirm that you want to add all the terminals in the group to the new group?',
        delGroupTitle:'Delete Group',
        delGroupConfirm:'Are you sure to delete this group and move the terminals back to the terminal pool?',
        editFormTitle:'edit group',
        importParamTitle:'import Param',
        importFile:'import param file',
        appName:'Application Name',
        terminalPool:'Terminal Pool',
        group:'Terminal Group',
        newGroup:'New Group'
      },
      key:{
        searchLabel:"UseFlag",
        searchPlace:"select UseFlag",
        addFormTitle:"add Key",
        deleteConfirm:"Are you sure to delete this key?",
        importFormTitle:"Import Key",
        selectKey:"Select Key",
        description:"Description",
        tmsCode:"TMS Code",
        tmk:"TMK",
        tak:"TAK",
        checksum:"Check Sum",
        tmkReferenceNo:"Reference Number Of TMK",
        filler:"Filler",
        createTime:"Create Time"
      },
      terminal:{
        searchLabel:"Terminal",
        merchant:"Merchant",
        keyStatus:"Key Status",
        status:"Status",
        HardwareVersion:"Hardware Version",
        SoftwareVersion:"Software Version",
        addFormTitle:"add terminal",
        importFormTitle:"Import Key",
        logFormTitle:"Terminal Log",
        selectKey:"Select Key",
        deleteConfirm:"Are you sure to delete this terminal?",
        startConfirm:"Are you sure to start using this terminal?",
        stopConfirm:"Are you sure to block up this terminal?",
        // 参数
        addParamFormTitle:'add Param',
        paramName:'Param Name',
        paramValue:'Param Value',
        paramStatus:'Param Status',
        parameter:'Parameter',
        memo:'memo',
        editParamFormTitle:'edit Param',
        deleteParamFormTitle:'delete Param',
        publicPrivate:'only 0(public) or 1(private)'
      }
    },
    merchantManage:{
      merchant:{
        name:"Merchant Name",
        namePlace:"enter Merchant Name",
        artificial:"Juridical Person",
        status:"Status",
        id:"Merchant ID",
        businessName:"Registered Name",
        IdNumber:"Juridical Person ID",
        businessAddr:"Merchant Addr",
        regAddr:"Register Address",
        mobileNo:"Tel",
        terminal:"Terminal",
        addFormTitle:"add merchant",
        editFormTitle:"edit merchant",
        detailFormTitle:"merchant details",
        deleteConfirm:"Are you sure to delete this merchant?",
        startConfirm:"Are you sure to start using this merchant?",
        stopConfirm:"Are you sure to block up this merchant?",
        terminalId:"Terminal Id",
        basicInfo:"Basic Info",
        terminalInfo:"Terminal Info"
      }
    },
    ...enLocale
  },
  zh: {
    loadingText:"正在加载...",
    emptyText:"暂无数据",
    language:"English",
    search:"查询",
    reset:"重置",
    changePwd:"修改密码",
    logout:"退出",
    operation:"操作",
    terOpt:'终端操作',
    perOpt:'参数操作',
    ok:"确定",
    cancel:"取消",
    oldPwd:"原密码",
    newPwd:"新密码",
    confirmPwd:"确认密码",
    prompt:"提示",
    exitConfirm:"确定要退出系统？",
    pwdValidMsg:"两次密码输入不一致",
    remark:"备注",
    selectFile:"选择文件",
    selectOneFile:"请选择一个文件",
    selectDate:"选择日期",
    selectOneData:"请至少选择一条数据",
    version:"版本号",
    downloadFlag:"下载标志",
    forceDownload:"强制下载",
    unforcedDownload:"非强制下载",
    createTime:"创建时间",
    updateTime:"更新时间",
    hasTerminal:"没有可选终端",
    selectData:"请选择一条数据",
    tel:"联系电话",
    address:"联系地址",
    linkman:"联系人",
    deviceSn:"终端硬件序列号",
    mchnt:"商户名称",
    requiredBlur:"此项不可为空",
    length32:"最多可以输入32个字符",
    length64:"最多可以输入64个字符",
    length128:"最多可以输入128个字符",
    length256:"最多可以输入256个字符",
    number:"请输入数字",
    phone:"请输入有效的电话号码",
    versionRules:"请输入有效的版本号",
    seri:"序号",
    noDev:"该组没有终端",
    selDev:"此组终端已被选中",
    AddSuccess:"添加成功",
    noTernimal:"没有设备",
    systemManage: {
      role:{
        searchLabel:"角色名称",
        searchPlaceHolder:"输入角色名称",
        addFormTitle:"添加角色",
        editFormTitle:"编辑角色",
        configFormTitle:"配置权限",
        fieldId:"角色ID",
        fieldname:"角色名称",
        fieldremark:"角色描述",
        deleteConfirm:"确定要删除该角色？"
      },
      operator:{
        username:"用户名",
        realname:"真实姓名",
        role:"所属角色",
        organization:"所属机构",
        remark:"备注",
        tel:"联系电话",
        status:"状态",
        usernamePlace:"输入用户名称",
        realnamePlace:"输入用户真实姓名",
        addFormTitle:"添加用户",
        editFormTitle:"编辑用户",
        deleteConfirm:"确定要删除该用户？",
        unlockConfirm:"确定要解锁该用户？",
        resetConfirm:"确实要重置改用户密码？"
      },
      org:{
        searchPlace:"输入机构名称",
        level:"机构等级",
        name:"机构名称",
        id:"机构号",
        type:"机构类型",
        addFormTitle:"添加机构",
        editFormTitle:"编辑机构",
        parentOrg:"父机构",
        deleteConfirm:"确定要删除该机构？",
      },
      log:{
        username:"操作员",
        namePlace:"输入操作员名称",
        status:"操作状态",
        operate:"操作",
        time:"操作时间",
        org:"所属机构",
        ip:"ip地址"
      }
    },
    appManage:{
      app:{
        key:"应用编号",
        nameLabel:"应用名称",
        statusLabel:"应用状态",
        searchPlace:"输入应用名称",
        name:"应用名称",
        brandName:"所属厂商",
        terminalType:"终端类型",
        terminalModel:"终端型号",
        applicationIcon: "应用图标",
        status:"终端状态",
        addFormTitle:"添加应用",
        editFormTitle:"编辑应用",
        selectTerminal:"选择终端",
        packageDetails:"应用包详情",
        addpackageFormTitle:"添加应用包",
        selectPackage:"应用包",
        download:"下载",
        downloadConfirm:"确定要下载该应用包？",
        deleteConfirm:"确定要删除该应用？",
        onlineConfirm:"确定要上线该应用？",
        outlineConfirm:"确定要下线该应用？",
        deletePkgConfirm:"确定要删除该应用包?"
      },
      firmWare:{
        nameLabel:"固件名称",
        namePlace:"输入固件名称",
        nameVersion:"输入固件版本",
        addFormTitle:"添加固件",
        onlineConfirm:"确定上线该固件？",
        outlineConfirm:"确定下线该固件？",
        id:"固件Id",
        FolderPath:"文件夹路径",
        FilePath:"文件路径",
        status:"固件状态",
        download:"下载",
        selectFirmWare:"选择固件",
        deleteConfirm:'确定要删除该固件？'
      },
      document:{
        searchLabel:"文件名称",
        searchPlaceHolder:"输入文件名",
        importFormTitle:"上传文件",
        selectKey:"选择文件",
        docName:"文件名称",
        docDesc:"文件描述",
        createdDatetime:"创建时间",
        deleteConfirm:'确定要删除该文件？'
      }
    },
    parameterManage:{
      para:{
        serialLabel:"终端序列号",
        versionLabel:"终端版本号",
        serialPlace:"输入终端序列号",
        versionPlace:"输入版本号",
        TPDU:"TPDU",
        addFormTitle:"添加终端应用参数",
        addMchntFormTitle:"添加商户参数",
        editMchntFormTitle:"编辑商户参数",
        addTpduFormTitle:"添加tpdu参数",
        terminalSerial:"终端序列号",
        serverParameter:"服务器通讯参数",
        serverParameter1:"备用服务器通讯参数1",
        serverParameter2:"备用服务器通讯参数2",
        tpduDetails:"终端应用tpdu参数",
        mchntDetails:"终端应用MCHNT参数",
        code:"序号",
        value:"参数值",
        type:"类型",
        currency:"途径",
        mchntName:"商户名称"
      },
      posp:{
        paramNo:"取用序号",
        paramType:"参数类型",
        paramVer:"参数版本号",
        createOprater:"创建人",
        paramVal:"参数值",
        addFormTitle:"添加POSP参数",
        editFormTitle:"编辑POSP参数",
        deleteConfirm:"确定删除该参数？"
        
      }
    },
    terminalManage:{
      brand:{
        searchLabel:"厂商名称",
        searchPlace:"输入厂商名称",
        addFormTitle:"添加厂商",
        editFormTitle:"编辑厂商",
        deleteConfirm:"确定要删除该厂商？",
        name:"厂商名称"
      },
      model:{
        type:"终端类型",
        model:"终端型号",
        addFormTitle:"添加型号",
        editFormTitle:"添加型号",
        deleteConfirm:"确定要删除该型号？",
      },
      key:{
        searchLabel:"状态",
        searchPlace:"请选择状态",
        addFormTitle:"添加秘钥",
        deleteConfirm:"确定删除此秘钥?",
        importFormTitle:"导入秘钥",
        selectKey:"选择密钥",
        description:"描述",
        tmsCode:"TMS Code",
        tmk:"终端主密钥",
        tak:"TAK",
        checksum:"校验值",
        tmkReferenceNo:"TMK参考号码",
        filler:"补充说明",
        createTime:"创建时间"
      },
      terminal:{
        searchLabel:"终端",
        merchant:"绑定商户",
        keyStatus:"密钥状态",
        status:"终端状态",
        HardwareVersion:"终端硬件版本号",
        SoftwareVersion:"终端软件版本号",
        addFormTitle:"添加终端",
        importFormTitle:"导入密钥",
        logFormTitle:"终端日志信息",
        selectKey:"选择密钥",
        deleteConfirm:"确定要注销该终端？",
        startConfirm:"确定要启用该终端？",
        stopConfirm:"确定要停用该终端？",
        // 参数
        addParamFormTitle:'添加参数',
        paramName:'参数名称',
        paramValue:'参数值',
        paramStatus:'参数状态',
        parameter:'参数说明',
        memo:'备忘录',
        editParamFormTitle:'修改参数',
        deleteParamFormTitle:'删除参数',
        publicPrivate:'只能是0（公有）/1（私有）'
      },
      devGroup:{
        searchLabel:"组名",
        searchPlaceHolder:"输入组名",
        modleName:"终端型号",
        creOpt:"创建人",
        addFormTitle:"创建组",
        termModel:"终端",
        selGroup:"选择组",
        transPlace:"输入终端序列号",
        copyModel:"复制来自其他组/终端的所有数据",
        deviceSn:"终端序列号",
        addGroupTitle:"复制所有数据",
        devGroupTitle:'确认要将组中的所有终端添加到新组中?',
        delGroupTitle:'删除组',
        delGroupConfirm:'确定删除该组并将这些终端移回终端池?',
        editFormTitle:'修改组',
        importParamTitle:'导入参数',
        importFile:'导入参数文件',
        appName:'应用名称',
        terminalPool:'终端池',
        group:'终端组',
        newGroup:'新终端组'
      },
    },
    merchantManage:{
      merchant:{
        name:"商户名称",
        namePlace:"输入商户名称",
        artificial:"法人代表",
        status:"商户状态",
        id:"商户ID",
        businessName:"商户经营名称",
        IdNumber:"法人代表证件号",
        businessAddr:"通讯地址",
        regAddr:"注册地址",
        mobileNo:"商户手机号",
        terminal:"已添加终端",
        addFormTitle:"添加商户",
        editFormTitle:"编辑商户",
        detailFormTitle:"商户详情",
        deleteConfirm:"确定要注销该商户？",
        startConfirm:"确定启用该商户？",
        stopConfirm:"确定停用该商户？",
        terminalId:"终端编号",
        basicInfo:"基本信息",
        terminalInfo:"终端信息"
      }
    },
    ...zhLocale
  }
}